### ISSUE TITLE
Text blocks ignore newlines

### ISSUE THREAD

**Issue by AprilSylph** [AprilSylph/Outbox-for-Tumblr#16]
Tumblr supports newlines within text blocks, which are respected. This extension should do the same.

```css
[data-block="text"] {
  white-space: pre-line;
  overflow-wrap: break-word;
}
```
